export const SET_USER_INFO_REQUESTED = 'SET_USER_INFO_REQUESTED';

export const SET_USER_INFO_SUCCEEDED = 'SET_USER_INFO_SUCCEEDED';

export const SET_USER_INFO_FAILED = 'SET_USER_INFO_FAILED';


export const GET_USER_INFO_REQUESTED = 'GET_USER_INFO_REQUESTED';

export const  GET_USER_INFO_SUCCEEDED = ' GET_USER_INFO_SUCCEEDED';

export const  GET_USER_INFO_FAILED = ' GET_USER_INFO_FAILED';
